WITH DISCOUNT_INFO AS (
    SELECT 
        CAR_TYPE, MAX(DISCOUNT_RATE) AS DISCOUNT_RATE
    FROM
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE 
        DURATION_TYPE IN ('7일 이상', '30일 이상')
        AND CAR_TYPE IN ('세단', 'SUV')
    GROUP BY
        CAR_TYPE
),

AVAILABLE_CARS AS (
    SELECT
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE
    FROM
        CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN
        CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        ON C.CAR_ID = H.CAR_ID
        AND (
            H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01'
        )
    WHERE
        C.CAR_TYPE IN ('세단', 'SUV')
        AND H.HISTORY_ID IS NULL
    ORDER BY C.CAR_ID
)

SELECT 
    AC.CAR_ID, 
    AC.CAR_TYPE,
    ROUND(AC.DAILY_FEE * 30 * (1 - DI.DISCOUNT_RATE / 100)) AS FEE
FROM
    DISCOUNT_INFO DI
JOIN
    AVAILABLE_CARS AC
    ON DI.CAR_TYPE = AC.CAR_TYPE
WHERE
    ROUND(AC.DAILY_FEE * 30 * (1 - DI.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 2000000
ORDER BY
    3 DESC,
    2 ASC,
    1 DESC;