WITH RENTAL_INFO AS (
    SELECT 
        C.DAILY_FEE, 
        C.CAR_TYPE, 
        H.CAR_ID, 
        H.HISTORY_ID,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS PERIOD,
        CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE 'NONE'
        END AS DURATION_TYPE
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN 
        CAR_RENTAL_COMPANY_CAR C 
    ON 
        H.CAR_ID = C.CAR_ID
    WHERE 
        C.CAR_TYPE = '트럭'
)

SELECT 
    I.HISTORY_ID,
    FLOOR(I.DAILY_FEE * I.PERIOD * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM 
    RENTAL_INFO I
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
ON 
    I.CAR_TYPE = P.CAR_TYPE 
    AND I.DURATION_TYPE = P.DURATION_TYPE
ORDER BY 
    FEE DESC, I.HISTORY_ID DESC;
