WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME
    WHERE HOUR < 23
)

SELECT 
    T.HOUR AS HOUR, 
    COUNT(O.ANIMAL_ID)
FROM 
    TIME T
LEFT JOIN
    ANIMAL_OUTS O
    ON T.HOUR = HOUR(O.DATETIME)
GROUP BY
    T.HOUR;