WITH FRONTEND_CODES AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (
    SELECT 1
    FROM FRONTEND_CODES F
    WHERE D.SKILL_CODE & F.CODE != 0
)
ORDER BY 1;